---
http_interactions:
- request:
    method: get
    uri: http://www.viaggiatreno.it/viaggiatrenonew/resteasy/viaggiatreno/cercaNumeroTrenoTrenoAutocomplete/19
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Host:
      - www.viaggiatreno.it
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 28 Jun 2016 11:53:24 GMT
      Content-Length:
      - '72'
      Content-Type:
      - text/plain
      Content-Language:
      - en-US
    body:
      encoding: ASCII-8BIT
      string: |
        19 - CHIASSO|19-S01301
        19 - MILANO NORD CADORNA|19-N00001
    http_version: 
  recorded_at: Tue, 28 Jun 2016 11:53:24 GMT
recorded_with: VCR 3.0.3
