---
http_interactions:
- request:
    method: get
    uri: http://www.viaggiatreno.it/viaggiatrenonew/resteasy/viaggiatreno/andamentoTreno/S01700/1
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Host:
      - www.viaggiatreno.it
  response:
    status:
      code: 204
      message: No Content
    headers:
      Date:
      - Tue, 28 Jun 2016 11:53:24 GMT
      Content-Length:
      - '0'
      Content-Type:
      - text/plain
      Content-Language:
      - en-US
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Tue, 28 Jun 2016 11:53:24 GMT
recorded_with: VCR 3.0.3
